version: '3.9'

services:
    web:
        build: .
        container_name: "django"
        command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        expose:
        - 8000
        depends_on:
        - db_books
        env_file:
            - .env

    db_books:
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
        - pg_books:/var/lib/postgresql/data/
        env_file:
            - .env
    nginx:
        image: nginx
        container_name: "nginx"
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        - ./nginx-conf.d:/etc/nginx/conf.d
        depends_on:
            - web
        ports:
            - 80:80

volumes:
    pg_books:
    static_volume:
    media_volume:
