version: '3.9'

services:
    db_books:
        image: postgres:15
        container_name: db_books
        volumes:
            - ~/.pg/postgres_data/boooks:/var/lib/postgresql/data/
        env_file:
            - .env
    books_django:
        image: books_m:latest
        container_name: books_django
        depends_on:
            - db_books
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        ports:
            - 8000:8000
        env_file:
            - .env
        command: bash -c "python ./manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"

    nginx:
        build: 
            dockerfile: ./Dockerfile
            context: ./docker/nginx/
        container_name: books_nginx
        image: books_nginx
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        depends_on:
            - books_django
        ports:
            - 8001:8000


volumes:
    static_volume:
    media_volume:
