version: '3.9'

services:
    db_books:
        image: postgres:15
        container_name: db_books
        volumes:
            - ~/.pg/postgres_data/boooks:/var/lib/postgresql/data/
        env_file:
            - .env
    web:
        build: .
        container_name: "django"
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        expose:
            - 8000
        depends_on:
            - db_books

        env_file:
            - .env
    nginx:
        image: nginx
        container_name: "nginx"
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        - ./nginx-conf.d:/etc/nginx/conf.d
        depends_on:
            - web
        ports:
            - 80:80

volumes:
    static_volume:
    media_volume:
