version: '3.9'

services:
    web:
        build: .
        container_name: "django"
        command: python /book/manage.py runserver  --insecure 0.0.0.0:8000
        # command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
        - .:/book
        ports:
            - 8000:8000
        depends_on:
        - db_books
        environment:
        - static_volume:/book/static
        - media_volume:/book/media
        - "DJANGO_SECRET_KEY=)*_s#exg*#w+#-xt=vu8b010%%a&p@4edwyj0=(nqq90b9a8*n"
        - "DJANGO_DEBUG=True"
        - "DJANGO_SECURE_SSL_REDIRECT=False" # new
        - "DJANGO_SECURE_HSTS_SECONDS=0" # new
        - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" # new
        - "DJANGO_SECURE_HSTS_PRELOAD=False" # new
        - "DJANGO_SESSION_COOKIE_SECURE=False" # new
        - "DJANGO_CSRF_COOKIE_SECURE=False" # new

    db_books:
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
        - pg_books:/var/lib/postgresql/data/

        environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    nginx:
        image: nginx
        container_name: "nginx"
        volumes:
        - static_volume:/book/static
        - media_volume:/book/media
        - ./nginx-conf.d:/etc/nginx/conf.d
        depends_on:
            - web
        ports:
            - 80:80

volumes:
    pg_books:
    static_volume:
    media_volume:
