version: '3.9'
services:
    db_books:
        image: postgres:15
        container_name: db_books
        volumes:
            - ~/.pg/pg_data/books:/var/lib/postgresql/data/
        env_file:
            - .env
    books:
        build: .
        container_name: books
        depends_on:
            - db_books
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - 8000:8000
        
