version: '3.9'

services:
    db_books:
        image: postgres:15
        container_name: db_books
        volumes:
            - ~/.pg/postgres_data/boooks:/var/lib/postgresql/data/
        env_file:
            - .env
    web:
        image: books_m:latest
        # build: .
        container_name: books_django

        # command: python /code/manage.py runserver 0.0.0.0:8000

        command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000

        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        # ports:
        #     - 8000:8000
        expose:
            - 8000
        depends_on:
            - db_books

        env_file:
            - .env
    nginx:
        build: 
            dockerfile: ./Dockerfile
            context: ./docker/nginx/
        container_name: books_nginx
        # image: books_nginx
        volumes:
        - static_volume:/code/static
        - media_volume:/code/media
        depends_on:
            - web
        ports:
            - 1337:8000


volumes:
    static_volume:
    media_volume:
